baseURL: "https://yutingchen-econ.com/"
title: Yuting Chen
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv/
          weight: 1
        - name: Research
          url: papers/
          weight: 2
        - name: Teaching
          url: courses/
          weight: 3
        - name: About Me
          url: about/
          weight: 4

params:
    description: "This website hosts Yuting Chen's bio, curriculum vitae, research papers, teaching experience, and contact information."
    author: Yuting Chen
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yuting Chen
          subtitle: "I am a PhD candidate in Economics at Purdue University. My Committee members are [Timothy Cason](https://sites.google.com/view/tim-cason)(co-chair), [David Gill](https://gill-david.github.io/)(co-chair), [Yaroslav Rosokha](https://web.ics.purdue.edu/~yrosokha), and [Brian Roberson](https://business.purdue.edu/faculty/brobers/). My research focuses on **Behavioral and Experimental Economics**, with a particular interest in **social dilemma** and **coordination**. I'm also affiliated to the Vernon Smith Experimental Economics Laboratory [(VSEEL)](https://business.purdue.edu/centers/vseel/) at Purdue University.\n\nI will be a candidate for the 2026-2027 Job Market."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: CV
              url: cv/
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
            - name: About Me
              url: about/

    socialIcons:
        - name: Email
          url: mailto:chen4442@purdue.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=KmZe-g8AAAAJ
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Linkedin
          url: https://www.linkedin.com/in/yuting-chen-15316b289/
        - name: ORCiD
          url: https://orcid.org/0000-0002-8479-3794


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yuting Chen"
      iconSVG: '<svg width="22" height="22" viewBox="0 0 22 22"><rect width="22" height="22" fill="#6252BC"/></svg>'

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2